"""
Air Quality Data Reader

This module reads and displays the collected air quality data from the CSV file
generated by fetch_airdata.py. It provides a simple interface to view the
collected time-series data for analysis.

Author: Group 3 - Data Science Final Project
Date: 2025
Course: Data Science Essentials

Requirements:
    - pandas: Data manipulation and analysis library

Usage:
    Run the script to display the collected air quality data:
        python read_airdata.py
    
    The script will load the data from 'air_data.csv' and display:
    - Complete DataFrame with all collected records
    - Detailed JSON data for each record

Example:
    $ python read_airdata.py
    Timestamp            City     AQI  PM2.5  JSON
    2025-03-17 08:00:00  Bangkok   67     67  {...}
    ...

Note:
    This is a simple data viewer. For comprehensive analysis, use the
    main.ipynb Jupyter notebook which includes data cleaning, visualization,
    statistical testing, and machine learning models.
"""

import pandas as pd

# CSV file name containing the collected air quality data
CSV_FILE = "air_data.csv"

# Load the air quality data from CSV file
df = pd.read_csv(CSV_FILE)

# Display the complete DataFrame
print("=" * 80)
print("Air Quality Data - Complete Dataset")
print("=" * 80)
print(df)

# Display detailed JSON data for advanced analysis
print("\n" + "=" * 80)
print("Detailed JSON Data (for advanced parsing)")
print("=" * 80)
print(df['JSON'])