name: Collect Air Quality Data Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify a version for consistency

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run fetch_airdata.py
        env:
          AQICN_API_KEY: ${{ secrets.AQICN_API_KEY }}  # Use a secret for the API key
        run: python fetch_airdata.py

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add air_data.csv  # Target only the intended file
          if git diff-index --quiet HEAD; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Daily update of air_data.csv"
            git push https://x-access-token:${GH_PAT}@github.com/NusratBegum/ds-project.git HEAD:main
          fi
