name: Collect Air Quality Data Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run fetch_airdata.py
        run: python fetch_airdata.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'air_data.csv'
          message: 'Daily update of air quality data'
          github_token: ${{ secrets.GH_PAT }}
