name: Collect Air Quality Data Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for Git operations

      - name: Check working directory state
        run: |
          echo "Listing files:"
          ls -la
          echo "Git status:"
          git status
          echo "Git diff (if any changes):"
          git diff || echo "No differences found"

      - name: Pull latest changes from main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Use PAT for authentication
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull https://x-access-token:${GH_PAT}@github.com/NusratBegum/ds-project.git main --rebase
          echo "Pulled latest changes from main"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specific version for consistency

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run fetch_airdata.py
        env:
          AQICN_API_KEY: ${{ secrets.AQICN_API_KEY }}  # Pass API key as env variable
        run: python fetch_airdata.py || exit 1  # Fail if script fails

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Personal Access Token for authentication
        run: |
          git add air_data.csv
          if git diff-index --quiet HEAD; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Daily update of air_data.csv"
            git push https://x-access-token:${GH_PAT}@github.com/NusratBegum/ds-project.git HEAD:main
            echo "Pushed changes to main"
          fi
